# SPDX-FileCopyrightText: 2020 Henrik Sandklef <hesa@sandklef.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
FROM openjdk:8

RUN apt-get update && apt-get install -y pandoc poppler-utils jq wget make curl texlive-latex-recommended pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra



